version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: selfdriving
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro # SQL初期化スクリプト
    networks:
      - selfdriving-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d selfdriving"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/selfdriving
      DB_MODE: development # development mode for auto-creation
      BULK_INSERT_MAX_NUM: 1000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - selfdriving-network
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  selfdriving-network:
    driver: bridge
